### ISSUE TITLE
Awkward API Client

### ISSUE THREAD

**Issue by somazx** [RusticiSoftware/scormcloud-api-v2-client-ruby#8]
I understand that this API client code is auto generated by Swagger. But this is a very awkward client to use.

The README.md shows example code:
```ruby
RusticiSoftwareCloudV2.configure do |config|
  # Configure HTTP basic authorization: APP_NORMAL
  config.username = 'YOUR USERNAME'
  config.password = 'YOUR PASSWORD'

  # Configure OAuth2 access token for authorization: OAUTH
  config.access_token = 'YOUR ACCESS TOKEN'
end
```

Ignoring the fact that `username` and `password` aren't good variable names for what is actually app_id and secret_key, and ignoring the fact that the links further down to documentation are all broken. Ignoring the fact that nowhere is a link to basic request/response examples. Ignoring the fact that methods like getRegistration returns nil on success...

I'll focus on the issues around using a global config with an access_token.

The example is demonstrating setting a global default configuration with an access_token. However access_tokens should be short lived, and should be generated with narrow scope/permissions for each specific task. Right? An admin interface would ideally request a very different access_token scope than code checking learner progress in a course.

By default the behaviour of this client is such that the access_token will be shared across all clients instantiated - globally:

```ruby
c1 = RusticiSoftwareCloudV2::CourseApi.new
c2 = RusticiSoftwareCloudV2::CourseApi.new
c1.api_client.config === c2.api_client.config
> true
c1.api_client.config.access_token = "foo"
c2.api_client.config.access_token
> "foo"
```

In a multi-threaded environment (running Puma server), wouldn't changing the access_token to a less permissive scope affect code running simultaneously in another thread expecting a different access_token?

The README.md example code is similar to other common Rails initializer examples intended to be placed in a rails' apps config/initializers directory. Code that is ran once on startup of the server to initialize global values and services. Rails users are likely to see the example code and place it in an initializer not realizing they're creating a potential thread safety issue.

Furthermore the design/structure of the client makes it tedious to actually make isolated clients with isolated configs. You have to initialize a new configuration instance, set the access_token on it, then create the generic api_client passing in that config object, then finally initialize the api client for the domain (ie RegistrationApi) passing in the generic api_client.

For example:
```ruby
config = RusticiSoftwareCloudV2::Configuration.new
config.access_token = unique_oauth_token_for_this_purpose
api_client = RusticiSoftwareCloudV2::ApiClient.new(config)
client = RusticiSoftwareCloudV2::RegistrationApi.new(api_client)

#finally we can use our client
client.get_registration_configuration
```

If you don't manually initialize config and api_client the API library will default to the global default config/api_client.

**Comment by somazx** [comment]
I'd expect the access_token to be stored in the client instance - not the config - so it is an isolated property of the client instance.

**Comment by mjschuetze102** [comment]
Apologies for the delay here. We are currently in the process of updating all of our client libraries. As part of this process, we went through and updated our READMEs. This included not only removing the auto-generated links at the base of the page, but also working sample code of a multitude of endpoints. This includes basic request/response examples for getting registration progress, retrieving an OAuth token and creating a new API object with the updated auth, etc.

With the new changes, we have made sure to call out the fact that the default configuration is shared across API objects unless otherwise specified. We have also included an example of how to set OAuth tokens for a specific API object like you have shown above. Unfortunately, we don't have much control over how swagger generates the interaction between Config/ ApiClient/ Api object, and in truth, it is different between each of the languages. Some do follow what you had suggested in terms of having the auth as part of the API object instead of Configuration, others pass the configuration directly to the API object, etc. At this point, we are stuck following the different paradigms in each of the generated templates in order to keep the amount of changes required to update our library to a minimum.

Lastly (and probably least relevant), GetRegistration indeed will return nil on success. The reason behind that is the request being made is a HEAD request, which shouldn't return data anyway. If you do want to work with the headers of a request, the `with_http_info` should be used instead (we are adding a couple of endpoints that will use headers, with plans to expand this paradigm further in the future). This will allow you to see the values returned from the HEAD request, but for this endpoint there is nothing of importance returned. The GetRegistration endpoint in particular is only used to check for the existence of a registration, not any information about the registration. The relevant endpoint is instead GetRegistrationProgress, which provides detailed information about the registration and their progress through a course.

**Comment by mjschuetze102** [comment]
Our latest release has the updated [README](https://github.com/RusticiSoftware/scormcloud-api-v2-client-ruby#sample-code) with sample code for working with our library. Please let us know if there is anything else we can improve upon with our documentation.
